import{a as S,S as y,i as g}from"./assets/vendor-6e0bf343.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const t of o)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(o){const t={};return o.integrity&&(t.integrity=o.integrity),o.referrerPolicy&&(t.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?t.credentials="include":o.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(o){if(o.ep)return;o.ep=!0;const t=s(o);fetch(o.href,t)}})();async function h(a,e){const s="43227181-d0d7712551e06c0c43f074b98",o="https://pixabay.com/api/";try{const t=await S.get(o,{params:{key:s,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}});if(t.status!==200)throw new Error("Failed to fetch images");return!t.data.hits||t.data.hits.length===0?{data:[],error:"No images found"}:{data:t.data,error:null}}catch(t){return{data:[],error:t.message}}}function b(){document.querySelector(".loader").style.display="block"}function v(){document.querySelector(".loader").style.display="none"}const q=new y(".gallery a",{captionDelay:250,captionsData:"alt"}),p=document.querySelector(".gallery");function I(a){return a.map(({webformatURL:e,largeImageURL:s,tags:i,likes:o,views:t,comments:l,downloads:L,id:x})=>`<li class="gallery-item">
          <a href="${s}" id="image-${x}">
              <img src="${e}" alt="${i}" width="360">
          </a>
          <div class="image-specs">
              <div class="specs-box"><p>Likes</p><p>${o}</p></div>
              <div class="specs-box"><p>Views</p><p>${t}</p></div>
              <div class="specs-box"><p>Comments</p><p>${l}</p></div>
              <div class="specs-box"><p>Downloads</p><p>${L}</p></div>
          </div>
      </li>`).join("")}function w(a){const e=I(a);p.insertAdjacentHTML("beforeend",e),q.refresh()}function E(){p&&(p.innerHTML="")}const r=document.querySelector(".load-more-btn"),u=document.getElementById("search-form"),f=document.getElementById("search-input"),m=document.querySelector(".search-btn");document.querySelector(".loader");document.querySelector(".gallery");const c=15;let n=1,d="";const $=new y(".gallery a",{captionDelay:250,captionsData:"alt"});document.addEventListener("DOMContentLoaded",()=>{r&&r.addEventListener("click",P),u&&u.addEventListener("submit",M)});async function M(a){if(a.preventDefault(),m.disabled=!0,b(),E(),r.style.display="none",d=f.value.trim(),d!==""){n=1;try{const e=await h(d,n);f.value="",!e||!e.data||!e.data.hits||e.data.hits.length===0||e.totalHits===0?g.info({title:"Information",message:"Вибачте, за вашим запитом не знайдено зображень. Будь ласка, спробуйте ще раз!",position:"topRight",backgroundColor:"red",maxWidth:"500px"}):(w(e.data.hits),$.refresh(),e.data.hits.length<c?r.style.display="none":r.style.display="block")}catch(e){console.error("Помилка під час отримання зображень:",e)}finally{m.disabled=!1,v()}}}async function P(){n+=1,b();try{const a=await h(d,n);w(a.data.hits);const e=a.totalHits;n*c>=e||a.data.hits.length<c?r.style.display="none":r.style.display="block",a.data.hits.length<c&&(r.style.display="none");const s=document.querySelector(".gallery-item");if(s){const i=s.getBoundingClientRect().height;window.scrollBy({left:0,top:i*2,behavior:"smooth"})}(a.data.hits.length===0||e>0&&n>=Math.ceil(e/c))&&(r.style.display="none",g.info({title:"Information",message:"Вибачте, але ви досягли кінця результатів пошуку.",position:"topRight",backgroundColor:"red",maxWidth:"500px"}),r.style.display="none")}catch(a){console.error("Error fetching images:",a),alert(a.message)}finally{v()}}
//# sourceMappingURL=commonHelpers.js.map
