import{a as L,S as m,i as f}from"./assets/vendor-6e0bf343.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();async function g(o,e){const r="43227181-d0d7712551e06c0c43f074b98",t="https://pixabay.com/api/";try{return{data:(await L.get(t,{params:{key:r,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data,error:null}}catch(s){return{data:[],error:s.message}}}function h(){document.querySelector(".loader").style.display="block"}function b(){document.querySelector(".loader").style.display="none"}const I=new m(".gallery a",{captionDelay:250,captionsData:"alt"}),p=document.querySelector(".gallery");function S(o){return o.map(({webformatURL:e,largeImageURL:r,tags:i,likes:t,views:s,comments:l,downloads:w,id:x})=>`<li class="gallery-item">
          <a href="${r}" id="image-${x}">
              <img src="${e}" alt="${i}" width="360">
          </a>
          <div class="image-specs">
              <div class="specs-box"><p>Likes</p><p>${t}</p></div>
              <div class="specs-box"><p>Views</p><p>${s}</p></div>
              <div class="specs-box"><p>Comments</p><p>${l}</p></div>
              <div class="specs-box"><p>Downloads</p><p>${w}</p></div>
          </div>
      </li>`).join("")}function v(o){const e=S(o);p.insertAdjacentHTML("beforeend",e),I.refresh()}function q(){p&&(p.innerHTML="")}const a=document.querySelector(".load-more-btn"),$=document.getElementById("search-form"),u=document.getElementById("search-input"),y=document.querySelector(".search-btn");$.addEventListener("submit",B);a.addEventListener("click",E);const c=15;let n=1,d="";const P=new m(".gallery a",{captionDelay:250,captionsData:"alt"});async function B(o){if(o.preventDefault(),y.disabled=!0,h(),q(),a.style.display="none",d=u.value.trim(),d!==""){n=1;try{const e=await g(d,n);u.value="",!e||!e.data||!e.data.hits||e.data.hits.length===0||e.totalHits===0?f.info({title:"Information",message:"Вибачте, за вашим запитом не знайдено зображень. Будь ласка, спробуйте ще раз!",position:"topRight",backgroundColor:"red",maxWidth:"500px"}):(v(e.data.hits),P.refresh(),e.data.hits.length<c?a.style.display="none":a.style.display="block")}catch(e){console.error("Помилка під час отримання зображень:",e)}finally{y.disabled=!1,b()}}}async function E(){n+=1,h();try{const o=await g(d,n);v(o.data.hits);const e=o.totalHits;n*c>=e||o.data.hits.length<c?a.style.display="none":a.style.display="block",o.data.hits.length<c&&(a.style.display="none");const r=document.querySelector(".gallery-item");if(r){const i=r.getBoundingClientRect().height;window.scrollBy({left:0,top:i*2,behavior:"smooth"})}(o.data.hits.length===0||e>0&&n>=Math.ceil(e/c))&&(a.style.display="none",f.info({title:"Information",message:"Вибачте, але ви досягли кінця результатів пошуку.",position:"topRight",backgroundColor:"red",maxWidth:"500px"}),a.style.display="none")}catch(o){console.error("Error fetching images:",o),alert(o.message)}finally{b()}}
//# sourceMappingURL=commonHelpers.js.map
